version: '3.8'

services:
  # Redis for caching and sessions
  redis:
    image: redis:7-alpine
    container_name: ekomart-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - ekomart-network
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    command: redis-server --appendonly yes --maxmemory 200mb --maxmemory-policy allkeys-lru

  # Next.js Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ekomart-app
    restart: unless-stopped
    environment:
      # MongoDB Atlas Connection
      MONGODB_URI: ${MONGODB_URI}
      
      # NextAuth
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      
      # Email Configuration
      EMAIL_SERVICE: ${EMAIL_SERVICE}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      EMAIL_FROM: ${EMAIL_FROM}
      EMAIL_FROM_NAME: ${EMAIL_FROM_NAME}
      
      # Legacy SMTP variables (for compatibility)
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      
      # Redis
      REDIS_URL: redis://redis:6379
      
      # App Configuration
      NODE_ENV: production
      PORT: 3000
      
      # File Upload
      UPLOAD_DIR: /app/uploads
      MAX_FILE_SIZE: 10485760
      
      # Security
      JWT_SECRET: ${JWT_SECRET}
      
      # Payment (if using)
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_PUBLISHABLE_KEY: ${STRIPE_PUBLISHABLE_KEY}
      
      # Other services
      BCRYPT_ROUNDS: 12
      
      # Performance optimizations
      NODE_OPTIONS: --max-old-space-size=1536
    volumes:
      - uploads_data:/app/uploads
      - ./public/uploads:/app/public/uploads
    depends_on:
      - redis
    networks:
      - ekomart-network
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: ekomart-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - nginx_logs:/var/log/nginx
    depends_on:
      - app
    networks:
      - ekomart-network
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis_data:
    driver: local
  uploads_data:
    driver: local
  nginx_logs:
    driver: local

networks:
  ekomart-network:
    driver: bridge