version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: ekomart-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - mongodb_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - ekomart-network
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  # Redis for caching and sessions
  redis:
    image: redis:7-alpine
    container_name: ekomart-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - ekomart-network
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  # Next.js Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ekomart-app
    restart: unless-stopped
    environment:
      # Database
      MONGODB_URI: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb:27017/${MONGO_DATABASE}?authSource=admin
      
      # NextAuth
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      
      # Email Configuration
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      
      # Redis
      REDIS_URL: redis://redis:6379
      
      # App Configuration
      NODE_ENV: production
      PORT: 3000
      
      # File Upload
      UPLOAD_DIR: /app/uploads
      MAX_FILE_SIZE: 10485760
      
      # Security
      JWT_SECRET: ${JWT_SECRET}
      
      # Payment (if using)
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_PUBLISHABLE_KEY: ${STRIPE_PUBLISHABLE_KEY}
      
      # Other services
      BCRYPT_ROUNDS: 12
    volumes:
      - uploads_data:/app/uploads
      - ./public/uploads:/app/public/uploads
    depends_on:
      - mongodb
      - redis
    networks:
      - ekomart-network
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: ekomart-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
    networks:
      - ekomart-network
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local
  uploads_data:
    driver: local

networks:
  ekomart-network:
    driver: bridge
